### ISSUE TITLE
询问关于加入印记中文组织

### ISSUE THREAD

**Issue by XieZongChen** [watonyweng/watonyweng#1]
你好，很开心 Vitest 能有印记中文组织的加入，之前我们的翻译流程各方面不太流畅，导致中文文档无法实时同步。有你们的加入，流程就显得正规许多。经过这段时间无声的配合 😁，我想加入这个组织一起贡献一份力，请问该如何加入呢？

**Comment by XieZongChen** [comment]
@watonyweng

**Comment by watonyweng** [comment]
@amadeus711 感谢你参与开源，加入 @docschina 需要 QC-L 邀请加入，我协助你申请加入。

**Comment by watonyweng** [comment]
@amadeus711 已经发送邀请了，请访问 [docschina](https://github.com/docschina) 查看。

**Comment by XieZongChen** [comment]
已加入成功，祝今后合作愉快😄
